### ISSUE TITLE
IndexError: list index out of range - ACOLITE generic Sentinel 2A

### ISSUE THREAD

**Issue by hanamthang** [acolite/acolite#1]
Hi Quinten, 

When I applied the ACOLITE generic to Sentinel-2A, this error appeared: 
```
Running generic ACOLITE processing - Generic Version Public Beta - April 2021
Run ID - 20210425_164803
/run/media/metal/d6d05414-194e-4f08-bb20-754d8b61789f/home/metal/Documents/research_paper/sg_mapping2016/S2A_OPER_PRD_MSIL1C_PDMC_20160413T231153_R075_V20160413T032321_20160413T032321.SAFE
/run/media/metal/d6d05414-194e-4f08-bb20-754d8b61789f/home/metal/Documents/research_paper/sg_mapping2016/S2A_OPER_PRD_MSIL1C_PDMC_20160413T231153_R075_V20160413T032321_20160413T032321.SAFE/Rrs1/acolite_run_20210425_164803_l1r_settings.txt
Starting conversion of 1 scenes
Starting conversion of /run/media/metal/d6d05414-194e-4f08-bb20-754d8b61789f/home/metal/Documents/research_paper/sg_mapping2016/S2A_OPER_PRD_MSIL1C_PDMC_20160413T231153_R075_V20160413T032321_20160413T032321.SAFE
Importing metadata from S2A_OPER_MSI_L1C_TL_SGS__20160413T082456_A004219_T48QZD_N02.01
Reading per pixel geometry
Traceback (most recent call last):
  File "/run/media/metal/d6d05414-194e-4f08-bb20-754d8b61789f/home/metal/Documents/phd/atmospheric/acoliteg25421/launch_acolite.py", line 58, in <module>
    launch_acolite()
  File "/run/media/metal/d6d05414-194e-4f08-bb20-754d8b61789f/home/metal/Documents/phd/atmospheric/acoliteg25421/launch_acolite.py", line 52, in launch_acolite
    ac.acolite.acolite_run(args.settings, inputfile=inputfile, output=output)
  File "/run/media/metal/d6d05414-194e-4f08-bb20-754d8b61789f/home/metal/Documents/phd/atmospheric/acoliteg25421/acolite/acolite/acolite_run.py", line 89, in acolite_run
    ret = ac.acolite.acolite_l1r(bundle, setu_l1r)
  File "/run/media/metal/d6d05414-194e-4f08-bb20-754d8b61789f/home/metal/Documents/phd/atmospheric/acoliteg25421/acolite/acolite/acolite_l1r.py", line 64, in acolite_l1r
    l1r_files = ac.sentinel2.l1_convert(bundle, output=output_,
  File "/run/media/metal/d6d05414-194e-4f08-bb20-754d8b61789f/home/metal/Documents/phd/atmospheric/acoliteg25421/acolite/sentinel2/l1_convert.py", line 331, in l1_convert
    dval, dfoo = ac.sentinel2.detector_footprint(target_file, gml_files[0])
IndexError: list index out of range
```

Could you pls tell me what kind of this? Can I fix it now? 

The old version ACOLITE LS2 performed without error.

Many thank,
Thang

**Comment by acolite** [comment]
Hi Thang

Thanks for your feedback! This looks like it is an issue with finding the detector footprint files in the old file format. Please try the latest commit!

Perhaps it is worth upgrading to a more recent version of the L1C data as well.

Quinten

**Comment by hanamthang** [comment]
Thank you, Quinten. The latest commit worked, however another error appeared as follows: 

```
1 rhot_443
Traceback (most recent call last):
  File "/run/media/metal/d6d05414-194e-4f08-bb20-754d8b61789f/home/metal/Documents/phd/atmospheric/acoliteg25421/launch_acolite.py", line 58, in <module>
    launch_acolite()
  File "/run/media/metal/d6d05414-194e-4f08-bb20-754d8b61789f/home/metal/Documents/phd/atmospheric/acoliteg25421/launch_acolite.py", line 52, in launch_acolite
    ac.acolite.acolite_run(args.settings, inputfile=inputfile, output=output)
  File "/run/media/metal/d6d05414-194e-4f08-bb20-754d8b61789f/home/metal/Documents/phd/atmospheric/acoliteg25421/acolite/acolite/acolite_run.py", line 103, in acolite_run
    ret = ac.acolite.acolite_l2r(l1r, settings = setu, verbosity = verbosity)
  File "/run/media/metal/d6d05414-194e-4f08-bb20-754d8b61789f/home/metal/Documents/phd/atmospheric/acoliteg25421/acolite/acolite/acolite_l2r.py", line 347, in acolite_l2r
    if verbosity > 2: print(b, setu['dsf_spectrum_option'], '{:.3f}'.format(band_data[0,0]))
TypeError: unsupported format string passed to numpy.ndarray.__format__

```
Is it regarding the format of L1C product or something with the codes of ACOLITE?

**Comment by acolite** [comment]
It seems like a problem of the string formatting in the printout - does it help setting verbosity to 0 in your settings file to avoid this printout?

**Comment by hanamthang** [comment]
Could you clarify where should I change the `verbosity to 0`? My setting file has no option of `verbosity`. I checked the `acolite_run.py` in `acolite/acolite/acolite_run.py` , however the `verbosity` was set to 0 already. 

Please see the code attached: 
`def acolite_run(settings, inputfile=None, output=None, limit=None, verbosity=0):
    import datetime, os, mimetypes
    import acolite as ac`

**Comment by acolite** [comment]
That's the default verbosity in the function set to 0, in the default ACOLITE settings (config/defaults.txt) I set this to verbosity=5. You can just add a line in your exported settings file with verbosity=0.

I am not sure why the numpy formatting doesn't work though. Which version of Python/Numpy are you using? Which OS?

Quinten

**Comment by hanamthang** [comment]
Hi Quinten, 

I tried the latest commit, change verbosity to 0 in the settings file but another error appeared:

`Traceback (most recent call last):
  File "/run/media/metal/d6d05414-194e-4f08-bb20-754d8b61789f/home/metal/Documents/phd/atmospheric/acolite/launch_acolite.py", line 58, in <module>
    launch_acolite()
  File "/run/media/metal/d6d05414-194e-4f08-bb20-754d8b61789f/home/metal/Documents/phd/atmospheric/acolite/launch_acolite.py", line 52, in launch_acolite
    ac.acolite.acolite_run(args.settings, inputfile=inputfile, output=output)
  File "/run/media/metal/d6d05414-194e-4f08-bb20-754d8b61789f/home/metal/Documents/phd/atmospheric/acolite/acolite/acolite/acolite_run.py", line 103, in acolite_run
    ret = ac.acolite.acolite_l2r(l1r, settings = setu, verbosity = verbosity)
  File "/run/media/metal/d6d05414-194e-4f08-bb20-754d8b61789f/home/metal/Documents/phd/atmospheric/acolite/acolite/acolite/acolite_l2r.py", line 411, in acolite_l2r
    tmp = lutdw[lut]['rgi'][b]((gem.data_mem['pressure'+gk],
  File "/home/metal/anaconda3/envs/thang/lib/python3.9/site-packages/scipy/interpolate/interpolate.py", line 2496, in __call__
    xi = _ndim_coords_from_arrays(xi, ndim=ndim)
  File "interpnd.pyx", line 157, in scipy.interpolate.interpnd._ndim_coords_from_arrays
  File "interpnd.pyx", line 168, in scipy.interpolate.interpnd._ndim_coords_from_arrays
  File "<__array_function__ internals>", line 5, in broadcast_arrays
  File "/home/metal/anaconda3/envs/thang/lib/python3.9/site-packages/numpy/lib/stride_tricks.py", line 538, in broadcast_arrays
    shape = _broadcast_shape(*args)
  File "/home/metal/anaconda3/envs/thang/lib/python3.9/site-packages/numpy/lib/stride_tricks.py", line 420, in _broadcast_shape
    b = np.broadcast(*args[:32])
ValueError: shape mismatch: objects cannot be broadcast to a single shape`

Seem related to numpy? 

I am using numpy version 1.20.1, Python 3.9, OS Manjaro Linux (an Arch based distro).

**Comment by acolite** [comment]
Could you send me the log and settings files for this run by email?

Quinten

**Comment by hanamthang** [comment]
The setting and log files were sent to your email at ` quinten.vanhellemont@naturalsciences.be`. 

Please have a look.

**Comment by acolite** [comment]
Hi Thang

I have been able to process this scene on Mac OS and Arch Linux with no issues using Python 3.9.2 and numpy 1.20.2 (latest from conda-forge) as well as with older versions of those packages.  This makes me think it is an issue with your Python installation or the source data. Could you provide me a copy of the file you are trying to process?

I got the input file "S2A_OPER_MSI_L1C_TL_SGS__20160413T032520_20160413T082456_A004219_T48QZD_N02_01_01.zip" from EarthExplorer.
 
![S2A_MSI_2016_04_13_03_23_21_T48QZD_LapAn_L2R_rgb_rhos](https://user-images.githubusercontent.com/26734727/117015673-3d926700-acf2-11eb-9fc6-005922106fc5.png)
![S2A_MSI_2016_04_13_03_23_21_T48QZD_LapAn_L2R_rgb_rhot](https://user-images.githubusercontent.com/26734727/117015694-43884800-acf2-11eb-990c-92fefeefbb15.png)

Quinten

**Comment by hanamthang** [comment]
Thank you for your support. I tried to download another scene of Sentinel 2A, however still failed with the similar error `ValueError: shape mismatch: objects cannot be broadcast to a single shape`. 

Surprisingly, the scene of Sentinel 2A is successfully processed with the old version of acolite `acolite_ls2-master`. 

So, I am not sure which error stay behind this? 

I will try to reinstall new environment and see how it works.

Many thanks,
Thang

**Comment by acolite** [comment]
Hi Thang - let me know how it goes! I am unfortunately unable to replicate the error, so I though it may have been the L1 format. Since you have tried another S2 scene it seems to point to your Python environment.

**Comment by acolite** [comment]
Hi Thang - were you able to successfully run the S2 processing?

**Comment by hanamthang** [comment]
Hi Quinten, 

Yes, I successfully processed the Sentinel-2A with the Generic version of ACOLITE. 

Surprisingly, the ACOLITE worked with the data from GloVIS and default setting of verbose (5). I ordered another scene from Earth Explorer and they do not process the image, so I returned to my old one. 

Don't know what happened but now it worked. 

Many thanks,
Thang

**Comment by acolite** [comment]
Thanks Thang, will close the issue then! If you even find out what happened let me know!

Quinten
