### ISSUE TITLE
pyhdf.error.HDF4Error: SD (15): File is supported, must be either hdf, cdf, netcdf

### ISSUE THREAD

**Issue by eikeschuett** [acolite/acolite#2]
Hi Quinten,
I tried Acolite for some OLCI and MSI scenes today. For one scene (`S3B_OL_1_EFR____20210507T101152_20210507T101452_20210508T144844_0179_052_122_1980_LN1_O_NT_002.SEN3`) it worked fine, others resulted in a strange error message after the L1R-nc file was created. 

This is the error message for `S3A_OL_1_EFR____20180715T093613_20180715T093913_20180716T163123_0179_033_250_1980_MAR_O_NT_002.SEN3`:

```
[...]
Created C:/Users/eikes/Desktop/temp/acolite/L2/S3A_OLCI_2018_07_15_09_36_13_L1R.nc
Running acolite for C:/Users/eikes/Desktop/temp/acolite/L2/S3A_OLCI_2018_07_15_09_36_13_L1R.nc
Process Process-1:
Traceback (most recent call last):
  File "C:\Users\eikes\anaconda3\envs\acolite\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "H:\Eigene Dateien\Studium\Hiwi\acolite\acolite\acolite\acolite\acolite_gui.py", line 30, in run
    raise e
  File "H:\Eigene Dateien\Studium\Hiwi\acolite\acolite\acolite\acolite\acolite_gui.py", line 25, in run
    mp.Process.run(self)
  File "C:\Users\eikes\anaconda3\envs\acolite\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "H:\Eigene Dateien\Studium\Hiwi\acolite\acolite\acolite\acolite\acolite_run.py", line 103, in acolite_run
    ret = ac.acolite.acolite_l2r(l1r, settings = setu, verbosity = verbosity)
  File "H:\Eigene Dateien\Studium\Hiwi\acolite\acolite\acolite\acolite\acolite_l2r.py", line 79, in acolite_l2r
    anc = ac.ac.ancillary.get(gem.gatts['isodate'], clon, clat)
  File "H:\Eigene Dateien\Studium\Hiwi\acolite\acolite\acolite\ac\ancillary\get.py", line 51, in get
    anc_ozone = ac.ac.ancillary.interp_ozone(ozone_file, lon, lat, kind=kind)
  File "H:\Eigene Dateien\Studium\Hiwi\acolite\acolite\acolite\ac\ancillary\interp_ozone.py", line 16, in interp_ozone
    f = SD(file, SDC.READ)
  File "C:\Users\eikes\anaconda3\envs\acolite\lib\site-packages\pyhdf\SD.py", line 1429, in __init__
    _checkErr('SD', id, "cannot open %s" % path)
  File "C:\Users\eikes\anaconda3\envs\acolite\lib\site-packages\pyhdf\error.py", line 23, in _checkErr
    raise HDF4Error(err)
pyhdf.error.HDF4Error: SD (15): File is supported, must be either hdf, cdf, netcdf
Processing error:
SD (15): File is supported, must be either hdf, cdf, netcdf
Traceback (most recent call last):
  File "H:\Eigene Dateien\Studium\Hiwi\acolite\acolite\acolite\acolite\acolite_gui.py", line 25, in run
    mp.Process.run(self)
  File "C:\Users\eikes\anaconda3\envs\acolite\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "H:\Eigene Dateien\Studium\Hiwi\acolite\acolite\acolite\acolite\acolite_run.py", line 103, in acolite_run
    ret = ac.acolite.acolite_l2r(l1r, settings = setu, verbosity = verbosity)
  File "H:\Eigene Dateien\Studium\Hiwi\acolite\acolite\acolite\acolite\acolite_l2r.py", line 79, in acolite_l2r
    anc = ac.ac.ancillary.get(gem.gatts['isodate'], clon, clat)
  File "H:\Eigene Dateien\Studium\Hiwi\acolite\acolite\acolite\ac\ancillary\get.py", line 51, in get
    anc_ozone = ac.ac.ancillary.interp_ozone(ozone_file, lon, lat, kind=kind)
  File "H:\Eigene Dateien\Studium\Hiwi\acolite\acolite\acolite\ac\ancillary\interp_ozone.py", line 16, in interp_ozone
    f = SD(file, SDC.READ)
  File "C:\Users\eikes\anaconda3\envs\acolite\lib\site-packages\pyhdf\SD.py", line 1429, in __init__
    _checkErr('SD', id, "cannot open %s" % path)
  File "C:\Users\eikes\anaconda3\envs\acolite\lib\site-packages\pyhdf\error.py", line 23, in _checkErr
    raise HDF4Error(err)
pyhdf.error.HDF4Error: SD (15): File is supported, must be either hdf, cdf, netcdf
```
Do you have an idea what is going on and how to fix that?

Thank you!

**Comment by acolite** [comment]
Hi Eike

Perhaps something went wrong in the downloading of the ancillary files. Could you list the files you have in the MET data for 2018-07-15? I believe they should be in data/MET/2018/196 and data/MET/2018/197. 

Extracting the ancillary data seems to work at my end for this date. I have 4 NCEPR2 files of around 850KB, one AURAOMI file of around 200KB and a TOAST file of around 160KB for each of those two dates. A possible fix could be removing those two directories and trying again.

Quinten

**Comment by eikeschuett** [comment]
Hi Quinten,

After deleting the two folders and running Acolite again I end up with the same error and MET-files:

- /MET/2018/196/
    -  N201819600_MET_NCEPR2_6h.hdf.bz2
    - N201819600_O3_AURAOMI_24h.hdf
    - N201819606_MET_NCEPR2_6h.hdf.bz2
    - N201819612_MET_NCEPR2_6h.hdf.bz2
    - N201819618_MET_NCEPR2_6h.hdf.bz2
    - S20181960019623_TOAST.OZONE
- /MET/2018/197/
    - N201819700_MET_NCEPR2_6h.hdf.bz2

All files are only 35 KB. I tried with both Python on Windows and Python on Ubuntu WSL, but the error still occurs.

Eike

**Comment by acolite** [comment]
Hi Eike

Sounds like an unsuccessful download, could you check whether the files contain the EarthData landing page or another web page? E.g. using cat /MET/2018/196/N201819600_MET_NCEPR2_6h.hdf.bz2

I did add a check for files to be >50KB but it seems this has failed for some reason, perhaps how the file size is reported by Windows: https://github.com/acolite/acolite/blob/2ae20da25f9e64dcf4d9d234c314328f2b082046/acolite/ac/ancillary/download.py#L40
 
Quinten

**Comment by eikeschuett** [comment]
Hi Quinten, 

I tried to manually download the ancillary files the URLs from `download.py` and found the "error": I couldn't properly log in on EarthData because my account required some additional personal information... After fixing the account issue everything is working fine. 

Many thanks for your support!

**Comment by acolite** [comment]
Great Eike! Thanks for your message!

Quinten
