### ISSUE TITLE
S2MSI tiles may be overwritten

### ISSUE THREAD

**Issue by sentinel3** [acolite/acolite#36]
Hello, great work on this Acolite. I use it occasionally and it is getting more stable and supporting more functions!
I notice a small issue on S2MSI tiles with very similar names will be overwritten.  Because ESA publish some tiles in parts, for example: L1C_T14UPB_A027394_20220604T173105.zip --> S2B_MSIL1C_20220604T172859_N0400_R055_T14UPB_20220604T195127.SAFE
L1C_T14UPB_A027394_20220604T173938.zip --> S2B_MSIL1C_20220604T172859_N0400_R055_T14UPB_20220604T210440.SAFE
when I put them in the same folder and then apply acolite, they will both output as: `S2B_MSI_2022_06_04_17_39_47_T14UPB_L?R.nc` and therefore overwrite each other.  I can walk around by assigning different --output folder.

another issue I faced is to assign a polygon (projected, EPSG:36214) as the processing boundary, acolite reports an error as below, while the same file processing fine uses a simplified polygon or a rectangle (lat/lon) box. I think maybe the original polygon is too complicated. again, not really an issue if I assign corners.
```
Using limit from polygon envelope: [5572918.6559, 482074.41593660973, 6000535.743400099, 691416.3089801259]
Process Process-1:
Traceback (most recent call last):
  File "~\Anaconda3\envs\acolite\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "~\Documents\GitHub\acolite\acolite\acolite\acolite_gui.py", line 31, in run
    raise e
  File "~\Documents\GitHub\acolite\acolite\acolite\acolite_gui.py", line 26, in run
    mp.Process.run(self)
  File "~\Anaconda3\envs\acolite\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "~\Documents\GitHub\acolite\acolite\acolite\acolite_run.py", line 86, in acolite_run
    ret = ac.acolite.acolite_l1r(bundle, setu_l1r)
  File "~\Documents\GitHub\acolite\acolite\acolite\acolite_l1r.py", line 67, in acolite_l1r
    l1r_files, setu = ac.sentinel2.l1_convert(bundle, settings = setu)
  File "~\Documents\GitHub\acolite\acolite\sentinel2\l1_convert.py", line 238, in l1_convert
    dct_sub = ac.shared.projection_sub(dct, limit, four_corners=True)
  File "~\Documents\GitHub\acolite\acolite\shared\projection_sub.py", line 65, in projection_sub
    xsize = int(xrange[1]-xrange[0])
ValueError: cannot convert float NaN to integer
Processing error:
cannot convert float NaN to integer
Traceback (most recent call last):
  File "~\Documents\GitHub\acolite\acolite\acolite\acolite_gui.py", line 26, in run
    mp.Process.run(self)
  File "~\Anaconda3\envs\acolite\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "~\Documents\GitHub\acolite\acolite\acolite\acolite_run.py", line 86, in acolite_run
    ret = ac.acolite.acolite_l1r(bundle, setu_l1r)
  File "~\Documents\GitHub\acolite\acolite\acolite\acolite_l1r.py", line 67, in acolite_l1r
    l1r_files, setu = ac.sentinel2.l1_convert(bundle, settings = setu)
  File "~\Documents\GitHub\acolite\acolite\sentinel2\l1_convert.py", line 238, in l1_convert
    dct_sub = ac.shared.projection_sub(dct, limit, four_corners=True)
  File "~\Documents\GitHub\acolite\acolite\shared\projection_sub.py", line 65, in projection_sub
    xsize = int(xrange[1]-xrange[0])
ValueError: cannot convert float NaN to integer
```

Thank you,
Chui,

**Comment by acolite** [comment]
Hi Chui

For the polygon, make sure the coordinates are in decimal degrees. It appears your polygon is using projected coordinates (in metres?): Using limit from polygon envelope: [5572918.6559, 482074.41593660973, 6000535.743400099, 691416.3089801259]

Indeed the files may be overwritten if the granule sensing time is the same. Your tiles have the same sensing time, but a different processing time. Do both tiles contain a different geographical coverage (i.e. the data is split over these two tiles)? In that case you can perhaps you can merge those tiles during processing.

Quinten

**Comment by acolite** [comment]
Closing this issue, please see here for more details on merging tiles containing partial data: https://github.com/acolite/acolite/issues/45

For the following image I have used:
inputfile=S2B_MSIL1C_20220604T172859_N0400_R055_T14UPB_20220604T195127.SAFE,S2B_MSIL1C_20220604T172859_N0400_R055_T14UPB_20220604T210440.SAFE
merge_tiles=True
s2_dilate_blackfill=True

![S2B_MSI_2022_06_04_17_39_40_merged_L1R_rgb_rhot](https://user-images.githubusercontent.com/26734727/202859953-a320516e-6732-43f3-b061-7a34caea5b56.png)

I hope this helps!

Quinten
