### ISSUE TITLE
Non-rectangular Sentinel-2 image causes a crash

### ISSUE THREAD

**Issue by NOC-EO** [acolite/acolite#70]
Hello Quentin,

Many thanks for your excellent and accessible atmospheric correction tool.

I am processing a lot of Sentinel-2 images and some of them are not rectangular because are at the edge of a swath. Although I am just processing part of the image using the 'limit' option and my subset is fully within the image swath.

I am using the linux distribution directly that calls a library called "acolite" by issuing this command on your latest linux distribution:

`acolite_py_linux/dist/acolite/acolite --cli --settings=<my_setting_txt_file>`

Each time I get a non rectangular image I get the following error:

Traceback (most recent call last):
  File "launch_acolite.py", line 79, in <module>
  File "launch_acolite.py", line 73, in launch_acolite
  File "acolite/acolite/acolite_run.py", line 111, in acolite_run
  File "acolite/acolite/acolite_l1r.py", line 72, in acolite_l1r
  File "acolite/sentinel2/l1_convert.py", line 496, in l1_convert
KeyError: '1'

I have searched the forum and cannot find reference to this issue using and search words I can think of such as "partial", "slice" etc.

Here is an image that causes this issue - although obviously there are many thousands of such images in the archive:

S2B_MSIL1C_20200527T113319_N0500_R080_T30UUA_20230415T034945.SAFE

Many thanks for your time as always. Clive

**Comment by acolite** [comment]
Hi Clive

Processing of this scene obtained from CDSE works fine for me, both full tile and a limit subset over Penzance. I have tried a current pull of the Python code, and the binary release 20231023.0 on Linux, but encountered no issues. 

For example for limit = 50.05752598272957, -5.5709253920874175, 50.135343974825815, -5.381022429545425

![S2B_MSI_2020_05_27_11_37_23_T30UUA_L2R_rgb_rhos](https://github.com/acolite/acolite/assets/26734727/71bc88b9-3393-4498-a2be-a18084c2f82e)

From your report this seems to be an issue with the detector enumeration in the scene. Did you also obtain the scene from CDSE and are you sure the bundle is complete? Could you provide the exact settings and a processing log file?

Quinten

**Comment by NOC-EO** [comment]
Hello Quentin - I have just downloaded the same image from CDSE again as a test - previously I had been using the PEPS data portal from CNES - and I get the same error as before - this time I am using the Windows distribution from my laptop - its really strange because the only images that produce this error are from the edge of the swath.

This is the log I got just now:

2024-02-08 10:54:08: Running ACOLITE processing - Generic Version 20231023.0
2024-02-08 10:54:08: Python - win32 - 3.11.6 | packaged by conda-forge | (main, Oct  3 2023, 10:29:11) [MSC v.1935 64 bit (AMD64)]
2024-02-08 10:54:08: Platform - Windows 10 - AMD64 - 10.0.19045
2024-02-08 10:54:08: Run ID - 20240208_105406
2024-02-08 10:54:08: Identified D:/ReSOW/raw/S2B_MSIL1C_20200527T113319_N0500_R080_T30UUA_20230415T034945.SAFE as Sentinel-2 type
2024-02-08 10:54:09: Starting conversion of 1 scenes
2024-02-08 10:54:09: Starting conversion of D:/ReSOW/raw/S2B_MSIL1C_20200527T113319_N0500_R080_T30UUA_20230415T034945.SAFE
2024-02-08 10:54:10: Importing metadata from L1C_T30UUA_A016837_20200527T113319
2024-02-08 10:54:10: Using limit from polygon envelope: [50.05, -5.57, 50.37, -4.4]
2024-02-08 10:54:10: clip mask
2024-02-08 10:54:10: (3780, 8445)
2024-02-08 10:54:10: Reading per pixel geometry
2024-02-08 10:54:12: Computing band average per detector geometry
2024-02-08 10:54:12: Detector 8
2024-02-08 10:54:12: Detector 9
2024-02-08 10:54:12: Detector 10
2024-02-08 10:54:12: Detector 11
2024-02-08 10:54:13: Detector 12
2024-02-08 10:54:19: Computing band specific per detector geometry
2024-02-08 10:54:20: Computing band specific geometry - B1
2024-02-08 10:54:20: Computing band specific geometry - B1 Detector 8
2024-02-08 10:54:20: Computing band specific geometry - B1 Detector 9
2024-02-08 10:54:20: Computing band specific geometry - B1 Detector 10
2024-02-08 10:54:20: Computing band specific geometry - B1 Detector 11
2024-02-08 10:54:20: Computing band specific geometry - B1 Detector 12
2024-02-08 10:54:21: Computing band specific geometry - B2
2024-02-08 10:54:21: Computing band specific geometry - B2 Detector 1

**Comment by NOC-EO** [comment]
I didnt mean to close this thread

**Comment by NOC-EO** [comment]
here are the settings

## ACOLITE settings
## Written at 2024-02-08 10:54:08
copy_datasets=lon,lat,sza,vza,raa,rhot_*
s2_target_res=10
s2_write_vaa=False
s2_write_saa=False
rgb_rhot=True
rgb_rhos=True
rgb_rhog=True
map_l2w=False
ancillary_data=True
EARTHDATA_u=***
EARTHDATA_p=***
gains_toa=1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
offsets_toa=0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
dsf_aot_estimate=fixed
dsf_spectrum_option=intercept
dsf_wave_range=400,900
dsf_intercept_pixels=1000
resolved_geometry=True
geometry_per_band=True
geometry_res=60
geometry_fixed_footprint=False
luts_reduce_dimensions=True
dsf_residual_glint_correction=True
dsf_residual_glint_correction_method=default
glint_mask_rhos_wave=1600
glint_mask_rhos_threshold=0.05
glint_write_rhog_ref=False
glint_write_rhog_all=True
l2w_parameters=rhos_492,rhos_559,rhos_560,rhos_665,rhos_833,spm_nechad2016,tur_nechad2016
l2w_mask=True
l2w_mask_wave=1610
l2w_mask_threshold=0.03
l2w_mask_water_parameters=True
l2w_mask_negative_rhow=True
l2w_mask_cirrus=True
l2w_mask_cirrus_threshold=0.005
l2w_mask_high_toa=True
l2w_mask_high_toa_threshold=0.3
l2w_mask_smooth=True
l2w_mask_smooth_sigma=7
l1r_delete_netcdf=True
l2r_delete_netcdf=True
l2w_nc_compression=True
l2r_export_geotiff=False
l2w_export_geotiff=True
inputfile=D:/ReSOW/raw/S2B_MSIL1C_20200527T113319_N0500_R080_T30UUA_20230415T034945.SAFE
output=D:/ReSOW/Cornwall/SR
polygon=D:/ReSOW/acolite/cornwall.geojson
runid=20240208_105406
new_path=None

**Comment by NOC-EO** [comment]
note because I use the same setting for Sentinel-2A and B the l2w_parameters has both rhos_559 and rhos_560 so I can get away with using a single setting file

**Comment by acolite** [comment]
Hi Clive

It seems like the issue was the combination of 
```
geometry_per_band=True
geometry_fixed_footprint=False

```

I have now added a check whether a detector is in the band specific metadata which should avoid this crash: https://github.com/acolite/acolite/commit/c3f30b438e99b2a8cb7cbdc06e32ba7f64ff2377 

However, the origin of this problem is still there, gdal.Warp introduces new values in the detector footprint dataset when reading from the JP2 data and downsampling, e.g. from 10 to 60 m. These values occur near the border of the sensor, i.e. where the detector index goes from 1 to 0 or 12 to 0. I do not understand the mechanism that introduces these values, or why for example values larger than the maximum can be introduced. (Even when using resampleAlg=near or min in gdal.Warp.) This may mean that a few pixels at the edge of the sensor may be masked in the resulting angle datasets, and potentially in the output data.

Alternatively you can probably just use geometry_fixed_footprint=True which will use band 1 footprints for all bands. I did not see this problem occur for upsampling from 60 to 20 or 10 m.

I hope this helps!

Quinten
