### ISSUE TITLE
OSError: Failed to open file b'C:\\Users\\\xe9\x95\xbf\xe8\xbe\xbe\\AppData\\Local\\Temp\\scipy-nhmkek_a'

### ISSUE THREAD

**Issue by liuchangda-fio** [acolite/acolite#77]
**Hi ! Thanks again for your work on this software. I have some probs with:** 

D:\Acolite\acolite_py_win>dist\acolite\acolite --cli --settings=D:\Acolite\acolite_dongsha_settings.txt
Running generic ACOLITE processing - Generic Version 20210802.0
Run ID - 20240707_212549
D:/S2B_MSIL1C_20230423T023529_N0509_R089_T50QMH_20230423T042316.SAFE
D:/Acolite/acolite_run_20240707_212549_l1r_settings.txt
Starting conversion of 1 scenes
Starting conversion of D:/S2B_MSIL1C_20230423T023529_N0509_R089_T50QMH_20230423T042316.SAFE
Importing metadata from L1C_T50QMH_A032004_20230423T024658
Reading per pixel geometry
AttributeError: 'NoneType' object has no attribute 'close'
Exception ignored in: 'scipy.spatial.qhull._Qhull.__dealloc__'
Traceback (most recent call last):
  File "scipy\interpolate\ndgriddata.py", line 260, in griddata
AttributeError: 'NoneType' object has no attribute 'close'
Traceback (most recent call last):
  File "launch_acolite.py", line 71, in <module>
  File "launch_acolite.py", line 65, in launch_acolite
  File "acolite\acolite\acolite_run.py", line 101, in acolite_run
  File "acolite\acolite\acolite_l1r.py", line 66, in acolite_l1r
  File "acolite\sentinel2\l1_convert.py", line 311, in l1_convert
  File "acolite\shared\tiles_interp.py", line 50, in tiles_interp
  File "scipy\interpolate\ndgriddata.py", line 260, in griddata
  File "interpnd.pyx", line 280, in scipy.interpolate.interpnd.LinearNDInterpolator.__init__
  File "qhull.pyx", line 1839, in scipy.spatial.qhull.Delaunay.__init__
  File "qhull.pyx", line 269, in scipy.spatial.qhull._Qhull.__init__
  File "messagestream.pyx", line 36, in scipy._lib.messagestream.MessageStream.__init__
OSError: Failed to open file b'C:\\Users\\\xe9\x95\xbf\xe8\xbe\xbe\\AppData\\Local\\Temp\\scipy-nhmkek_a'
[14184] Failed to execute script 'launch_acolite' due to unhandled exception!

what can I should do?

**Comment by liuchangda-fio** [comment]
moreover, the OSError have different in many tries. This is another report:

D:\Acolite\acolite_py_win>dist\acolite\acolite --cli --settings=D:\Acolite\acolite_dongsha_settings.txt
Running generic ACOLITE processing - Generic Version 20210802.0
Run ID - 20240707_213906
D:/S2B_MSIL1C_20230423T023529_N0509_R089_T50QMH_20230423T042316.SAFE
D:/Acolite/acolite_run_20240707_213906_l1r_settings.txt
Starting conversion of 1 scenes
Starting conversion of D:/S2B_MSIL1C_20230423T023529_N0509_R089_T50QMH_20230423T042316.SAFE
Importing metadata from L1C_T50QMH_A032004_20230423T024658
Reading per pixel geometry
AttributeError: 'NoneType' object has no attribute 'close'
Exception ignored in: 'scipy.spatial.qhull._Qhull.__dealloc__'
Traceback (most recent call last):
  File "scipy\interpolate\ndgriddata.py", line 260, in griddata
AttributeError: 'NoneType' object has no attribute 'close'
Traceback (most recent call last):
  File "launch_acolite.py", line 71, in <module>
  File "launch_acolite.py", line 65, in launch_acolite
  File "acolite\acolite\acolite_run.py", line 101, in acolite_run
  File "acolite\acolite\acolite_l1r.py", line 66, in acolite_l1r
  File "acolite\sentinel2\l1_convert.py", line 311, in l1_convert
  File "acolite\shared\tiles_interp.py", line 50, in tiles_interp
  File "scipy\interpolate\ndgriddata.py", line 260, in griddata
  File "interpnd.pyx", line 280, in scipy.interpolate.interpnd.LinearNDInterpolator.__init__
  File "qhull.pyx", line 1839, in scipy.spatial.qhull.Delaunay.__init__
  File "qhull.pyx", line 269, in scipy.spatial.qhull._Qhull.__init__
  File "messagestream.pyx", line 36, in scipy._lib.messagestream.MessageStream.__init__
OSError: Failed to open file b'C:\\Users\\\xe9\x95\xbf\xe8\xbe\xbe\\AppData\\Local\\Temp\\scipy-4j8uuar6'
[4848] Failed to execute script 'launch_acolite' due to unhandled exception!

I have no idea about what happened

**Comment by acolite** [comment]
You are using an old version of ACOLITE (20210802) which does not support updates to the Sentinel-2 SAFE format in PB4 and 5. Could you update and try again?

Quinten

**Comment by liuchangda-fio** [comment]
It works! The Acolite is a crazy wonderful software. Thanks a lot!
