### ISSUE TITLE
export_geotiff error

### ISSUE THREAD

**Issue by PennyJClarke** [acolite/acolite#79]
Hi Acolite,

I would like to run Acolite and export a GeoTIFF format of an atmosphere correction instead of NetCDF, however, I am recieving an error.

In the settings.txt file, if I set the following to true:
l1r_export_geotiff=True
l2t_export_geotiff=True
l2r_export_geotiff=True
l2w_export_geotiff=True

The processing fails with an error, except if set all to false, the processing runs producing a NetCDF output. Myself and a colleague on a seperate machines have tried with no success to get the GeoTIFF output processing.

I am using a Windows 10 OS with an anaconda environment set up for acolite using your current installation instructions (environment created Thursday 8th August 2024).

My acolite settings were as follows (I have removed my user account and image id in the input and output links for sensitivty, though for info I am using Maxar WV2 data):
# ACOLITE settings
# Written at 2021-12-24 10:48:44
region_name=
# Comma separated list of bounding box coordinates of ROI in decimal degrees in S,W,N,E order.
# Useful for when you're looking at the same AOI over multiple timesteps, else limit=None
limit=None
output=/Users/Desktop/acolite/outputs_pc/
l2w_parameters=Rhos_*
dsf_path_reflectance=tiled
l1r_export_geotiff=True
l2t_export_geotiff=True
l2r_export_geotiff=True
l2w_export_geotiff=True
l1r_delete_netcdf=False
l2r_delete_netcdf=False
l2w_delete_netcdf=False
netcdf_compression=True
netcdf_compression_level=4
elevation=0
dem_pressure=False
glint_correction=True
glint_force_band=None
glint_mask_rhos_wave=1600
glint_mask_rhos_threshold=0.05
luts=ACOLITE-LUT-202110-MOD1,ACOLITE-LUT-202110-MOD2
slicing=False
##comma separated list with each full path name and full filename
inputfile=/Users/Desktop/acolite/inputs_pc/(image id removed from link for sensitivity)
runid=

I cd to the acolite file from anaconda prompt window.
I restore the setting.txt file once python ./launch_acolite.py is ran and open.
Then I run processing, receivign the following error (again I have removed my user account and image id in the input and output links for sensitivty)...

Running ACOLITE processing on win32
ACOLITE processing messages will be logged to file.
Running ACOLITE processing - Generic GitHub Clone c2024-08-09T15:37:51
Python - win32 - 3.12.5 | packaged by conda-forge | (main, Aug  8 2024, 18:24:51) [MSC v.1940 64 bit (AMD64)]
Platform - Windows 10 - AMD64 - 10.0.19045
Run ID -
Error:NCpathcvt: stat=-36 (NetCDF: Invalid argument)
Error:NCpathcvt: stat=-36 (NetCDF: Invalid argument)
Error:NCpathcvt: stat=-36 (NetCDF: Invalid argument)
/Users/Desktop/acolite/inputs_pc/(image id removed from link for sensitivity).XML
Identified /Users/Desktop/acolite/inputs_pc/(image id removed from link for sensitivity) as WorldView type
C:\Users\Anaconda3\envs\acolite_v2\Lib\site-packages\osgeo\gdal.py:312: FutureWarning: Neither gdal.UseExceptions() nor gdal.DontUseExceptions() has been explicitly called. In GDAL 4.0, exceptions will be enabled by default.
  warnings.warn(
2024-08-16T09:12:13 - Writing lat/lon
lat/lon computed from projection info
Error:NCpathcvt: stat=-36 (NetCDF: Invalid argument)
Process Process-1:
Traceback (most recent call last):
  File "C:\Users\Anaconda3\envs\acolite_v2\Lib\multiprocessing\process.py", line 314, in _bootstrap
    self.run()
  File "C:\Users\Desktop\acolite\acolite\acolite\acolite_gui.py", line 31, in run
    raise e
  File "C:\Users\Desktop\acolite\acolite\acolite\acolite_gui.py", line 26, in run
    mp.Process.run(self)
  File "C:\Users\Anaconda3\envs\acolite_v2\Lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Desktop\acolite\acolite\acolite\acolite_run.py", line 151, in acolite_run
    ret = ac.acolite.acolite_l1r(bundle)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Desktop\acolite\acolite\acolite\acolite_l1r.py", line 115, in acolite_l1r
    l1r_files, setu = ac.worldview.l1_convert(bundle, inputfile_swir = setu['inputfile_swir'], settings = setu)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Desktop\acolite\acolite\worldview\l1_convert.py", line 280, in l1_convert
    gemo.write('lon', lon)
  File "C:\Users\Desktop\acolite\acolite\gem\gem.py", line 166, in write
    self.nc = ac.output.nc_write(self.file, ds, data, dataset_attributes=ds_att,
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Desktop\acolite\acolite\output\nc_write.py", line 116, in nc_write
    nc = Dataset(ncfile, 'w', format=format)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "src\\netCDF4\\_netCDF4.pyx", line 2470, in netCDF4._netCDF4.Dataset.__init__
  File "src\\netCDF4\\_netCDF4.pyx", line 2107, in netCDF4._netCDF4._ensure_nc_success
PermissionError: [Errno 13] Permission denied: '/Users/Desktop/acolite/outputs_pc//(image id removed from link for sensitivity)_L1R.nc'
Processing error:
[Errno 13] Permission denied: '/Users/Desktop/acolite/outputs_pc//(image id removed from link for sensitivity)_L1R.nc'
Traceback (most recent call last):
  File "C:\Users\Desktop\acolite\acolite\acolite\acolite_gui.py", line 26, in run
    mp.Process.run(self)
  File "C:\Users\Anaconda3\envs\acolite_v2\Lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Desktop\acolite\acolite\acolite\acolite_run.py", line 151, in acolite_run
    ret = ac.acolite.acolite_l1r(bundle)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Desktop\acolite\acolite\acolite\acolite_l1r.py", line 115, in acolite_l1r
    l1r_files, setu = ac.worldview.l1_convert(bundle, inputfile_swir = setu['inputfile_swir'], settings = setu)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Desktop\acolite\acolite\worldview\l1_convert.py", line 280, in l1_convert
    gemo.write('lon', lon)
  File "C:\Users\Desktop\acolite\acolite\gem\gem.py", line 166, in write
    self.nc = ac.output.nc_write(self.file, ds, data, dataset_attributes=ds_att,
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Desktop\acolite\acolite\output\nc_write.py", line 116, in nc_write
    nc = Dataset(ncfile, 'w', format=format)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "src\\netCDF4\\_netCDF4.pyx", line 2470, in netCDF4._netCDF4.Dataset.__init__
  File "src\\netCDF4\\_netCDF4.pyx", line 2107, in netCDF4._netCDF4._ensure_nc_success
PermissionError: [Errno 13] Permission denied: '/Users/s0951644/Desktop/acolite/outputs_pc//(image id removed from link for sensitivity)_L1R.nc'

My colleague ran the code with similar settings.txt from a Windows 11 OS Windows powershell:
# ACOLITE settings
# Written at 2024-08-05 10:06:20
inputfile=/Users/Desktop/acolite/inputs_pc/(image id removed from link for sensitivity)
output=/Users/Desktop/acolite/outputs_pc/
polygon=None
l2w_parameters=Rhos_*
dsf_path_reflectance=tiled
glint_correction=True
glint_force_band=None
glint_mask_rhos_wave=1600
glint_mask_rhos_threshold=0.05
slicing=False
rgb_rhot=False
rgb_rhos=False
map_l2w=False
l2r_export_geotiff=True

Their output gave the following error:
RuntimeError: 'NETCDF: "link removed from link for sensitivity_l2R.nc":rhot_428' does not exist in the file system, and is not recognised as a supported dataset name.

Please can you advise why these errors may be recieved and how we can overcome them to achieve a atmospheric correction in GeoTIFF format.

Thank you for your time to support with guidance.

Best wishes

Penny

**Comment by acolite** [comment]
Hi Penny

I do not have access to many Maxar WV2 images, and if you could share this bundle just for debugging purposes that would be helpful. Perhaps the projection information is not copied over properly for the WV bundles so the GeoTIFF creation fails.

In the errors you posted it seems:
(1) like a file permission error, is this file open elsewhere, or was it created by a different process/user?
(2) this seems like an issue of reading the datasets from the NetCDF files using GDAL, which version of that package have they installed?

Quinten

**Comment by PennyJClarke** [comment]
Hi Quinten,

Thank you for your patience in hearing from me, it's been some time, a few other projects delayed my progress with the work associated with this issue. Returning to the issue, I have recently spoken with another Acolite user who said they have always been able to produce .tif files without issue, they I recommend instead of using Acolite from the user interface (running Python .\launch_acolite.py and restoring file settings in the user interface) that I run Acolite from Anaconda prompt directly using: 
python launch_acolite.py --cli --settings=C:\\Users\\myusername\\acolite\\FD_settings_v2.txt.

I wished to update you and let you know that in doing this I have been able to produce .tif outputs. It seems then that potentially the issue is resulting from the user interface alone, in case you wished to look into this further.

Thank you for your time and support. 

Best wishes

Penny
