### ISSUE TITLE
"NameError: name 'lut_nc' is not defined"

### ISSUE THREAD

**Issue by acolite** [acolite/acolite#8]
Dear Quinten,I encountered a problem when I ran it. This problem is "NameError: name 'lut_nc' is not defined". How do I do at this time?
Details are as follows:
Selected E:/BaiduNetdiskDownload/LC08_L1TP_119039_20201111_20201111_01_RT as input file.
Selected E:/Landsat8_aot as output directory.
Running ACOLITE processing on win32
ACOLITE processing messages will be logged to file.
Processing error:
name 'lut_nc' is not defined
Traceback (most recent call last):
  File "E:\Download\acolite-main\acolite-main\acolite\shared\lutnc_import.py", line 15, in lutnc_import
    nc = Dataset(lutnc)
  File "src\netCDF4\_netCDF4.pyx", line 2307, in netCDF4._netCDF4.Dataset.__init__
  File "src\netCDF4\_netCDF4.pyx", line 1925, in netCDF4._netCDF4._ensure_nc_success
FileNotFoundError: [Errno 2] No such file or directory: b'E:\\Download\\acolite-main\\acolite-main\\data/LUT/Gas/Gas_202106F.nc'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Download\acolite-main\acolite-main\acolite\acolite\acolite_gui.py", line 25, in run
    mp.Process.run(self)
  File "D:\python37\lib\multiprocessing\process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "E:\Download\acolite-main\acolite-main\acolite\acolite\acolite_run.py", line 118, in acolite_run
    ret = ac.acolite.acolite_l2r(l1r, settings = setu, verbosity = verbosity)
  File "E:\Download\acolite-main\acolite-main\acolite\acolite\acolite_l2r.py", line 134, in acolite_l2r
    rsr=rsrd['rsr'])
  File "E:\Download\acolite-main\acolite-main\acolite\ac\gas_transmittance.py", line 18, in gas_transmittance
    tg_hyp = ac.ac.gaslut_interp(sza, vza, pressure=pressure, waves=waves, lutconfig=lutconfig)
  File "E:\Download\acolite-main\acolite-main\acolite\ac\gaslut_interp.py", line 32, in gaslut_interp
    lut, meta = ac.shared.lutnc_import(lutnc)
  File "E:\Download\acolite-main\acolite-main\acolite\shared\lutnc_import.py", line 26, in lutnc_import
    print(lut_nc)
NameError: name 'lut_nc' is not defined

_Originally posted by @LH002 in https://github.com/acolite/acolite/issues/7#issuecomment-889624854_

**Comment by acolite** [comment]
The LUTs are now not bundled with acolite and should be retrieved from a separate repository (https://github.com/acolite/acolite_luts). Is your processing machine connected to the internet?

You can run the following to download the required LUTs for a given sensor:

`python launch_acolite.py --retrieve_luts --sensor L8_OLI 
`

Quinten

**Comment by LH002** [comment]
When I used the "python launch_acolite.py --retrieve_luts --sensor L8_OLI”, it had the same error. So I downloaded the file "acolite-lut-202102-mod1-0500mb" from the website_ L8_ "Oli. NC", in which folder do I need to put this file now?

**Comment by acolite** [comment]
The acolite_luts repository has a description of where to put the LUTs. In summary the file structure from acolite_luts needs to go in the acolite/data/LUT/ directory.

I would like to fix the problem with the automatic retrieval though! Could you post the full error when running the --retrieve_luts option? Do you have "requests" installed in your Python environment? Do you have write access to acolite/data/LUT?

**Comment by LH002** [comment]
Thank you for your helps! I downloaded these files in my computer. This problem was solved. But I encountered a new problem:"ValueError: array of sample points is empty" . These my run log:Restored settings file E:/Landsat8_aot/acolite_run_20210730_114108_l1r_settings.txt
Running ACOLITE processing on win32
ACOLITE processing messages will be logged to file.
Processing error:
array of sample points is empty
Traceback (most recent call last):
  File "E:\Download\acolite-main\acolite-main\acolite\acolite\acolite_gui.py", line 25, in run
    mp.Process.run(self)
  File "D:\python37\lib\multiprocessing\process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "E:\Download\acolite-main\acolite-main\acolite\acolite\acolite_run.py", line 118, in acolite_run
    ret = ac.acolite.acolite_l2r(l1r, settings = setu, verbosity = verbosity)
  File "E:\Download\acolite-main\acolite-main\acolite\acolite\acolite_l2r.py", line 1231, in acolite_l2r
    rsrd_o = ac.shared.rsr_dict(sensor_o)[sensor_o]
  File "E:\Download\acolite-main\acolite-main\acolite\shared\rsr_dict.py", line 31, in rsr_dict
    rsrd[fsensor]['wave_mu'] = ac.shared.rsr_convolute_dict(waves, waves, rsrd[fsensor]['rsr'])
  File "E:\Download\acolite-main\acolite-main\acolite\shared\rsr_convolute_dict.py", line 18, in rsr_convolute_dict
    band_response_hyper = np.interp(wave_hyper, rsr[band]['wave'], rsr[band]['response'], left=0, right=0)
  File "<__array_function__ internals>", line 6, in interp
  File "D:\python37\lib\site-packages\numpy\lib\function_base.py", line 1439, in interp
    return interp_func(x, xp, fp, left, right)
ValueError: array of sample points is empty

**Comment by acolite** [comment]
I think this error is solved by the new orange band RSR file uploaded yesterday: https://github.com/acolite/acolite/commit/01ee61eab8c3443a6713f5a47258a46fbff274c7

 Could you update to the last version of the code?

**Comment by LH002** [comment]
I will try it tomorrow,thank you.



---Original---
From: "Quinten ***@***.***&gt;
Date: Fri, Jul 30, 2021 18:04 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [acolite/acolite] "NameError: name 'lut_nc' is not defined" (#8)




 
I think this error is solved by the new orange band RSR file uploaded yesterday: 01ee61e
 
Could you update to the last version of the code?

**Comment by LH002** [comment]
I have a new problem. When I run this program, "DLL load failed", the specific log is as follows:Running ACOLITE processing on win32
ACOLITE processing messages will be logged to file.
Processing error:
DLL load failed:The specified module could not be found.
Traceback (most recent call last):
  File "E:\Download\acolite-main\acolite-main\acolite\acolite\acolite_gui.py", line 25, in run
    mp.Process.run(self)
  File "D:\python37\lib\multiprocessing\process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "E:\Download\acolite-main\acolite-main\acolite\acolite\acolite_run.py", line 135, in acolite_run
    ret = ac.acolite.acolite_l2w(l2r, settings=l2r_setu)
  File "E:\Download\acolite-main\acolite-main\acolite\acolite\acolite_l2w.py", line 23, in acolite_l2w
    import skimage.color
  File "D:\python37\lib\site-packages\skimage\__init__.py", line 127, in <module>
    from .util.dtype import (img_as_float32,
  File "D:\python37\lib\site-packages\skimage\util\__init__.py", line 17, in <module>
    from ._map_array import map_array
  File "D:\python37\lib\site-packages\skimage\util\_map_array.py", line 2, in <module>
    from ._remap import _map_array
ImportError: DLL load failed: The specified module could not be found.

**Comment by acolite** [comment]
Did the download from the acolite_luts GitHub work? Automatically or manually?

**Comment by LH002** [comment]
Manually

**Comment by acolite** [comment]
Perhaps the automatic download fails if you have insufficient rights to write at the target location? I have seen this in other systems.

Quinten

**Comment by LH002** [comment]
Yes. So I try to use manual download to solve this problem. Fortunately, this method is feasible.

**Comment by acolite** [comment]
Do you have the requests package installed in Python?

Quinten

**Comment by acolite** [comment]
I have added an alternative retrieval URL,  if you have still issues retrieving the LUTs, try uncommenting the second lut_url option in the config/config.txt:

https://github.com/acolite/acolite/blob/2d0f13fa287b992ea7aefe6a9be9e786b5888ed9/config/config.txt#L48-L52

Quinten
