### ISSUE TITLE
Issues with NetCDF trying to get GeoTiff's

### ISSUE THREAD

**Issue by Brent0423** [acolite/acolite#85]
Dear ACOLITE Development Team,

I'm writing out of frustration after spending four full days attempting to configure ACOLITE on my Mac M3 Pro Max. Despite following the general installation instructions and trying numerous configurations, I'm still unable to get the software working properly. I believe having Mac-specific setup instructions would be incredibly helpful, not just for me but for other Mac users as well.

Current Status (After 4 Days of Attempts):
1. Successfully installed:
   - ACOLITE (latest version)
   - GDAL 3.9.3
   - libgdal-jp2openjpeg
   - NetCDF4
   - All other required dependencies

2. Progress Made:
   - Can process Sentinel-2 data up to NetCDF creation
   - NetCDF files are created successfully
   - All required variables are present in the NetCDF files

3. Persistent Error:
   When attempting to convert NetCDF to GeoTIFF, receiving: RuntimeError: NETCDF:"/Users/brentsanford/Desktop/Output/S2A_MSI_2024_10_21_16_51_23_T16TEP_L1R.nc":raa: No such file or directory.

System Details:
- macOS on M3 Pro Max (ARM64)
- Python 3.9.20
- GDAL 3.9.3
- ACOLITE version: c2024-10-29T21:24:13

Specific Questions:
1. Do you have a dedicated installation guide for Mac systems, particularly Apple Silicon?
2. Are there known compatibility issues with GDAL/NetCDF on Mac ARM64?
3. Can you provide step-by-step conda environment setup instructions for Mac?
4. Are there specific GDAL configurations needed for Mac systems?

I've tried multiple approaches including:
- Different GDAL versions
- Various conda environment configurations
- Multiple NetCDF4 installations
- Different Python versions

Would it be possible to:
1. Share Mac-specific setup instructions?
2. Provide a working conda environment.yml file for Mac?
3. List any known workarounds for Mac systems?

I'm happy to provide any additional information.

Thank you for your time and assistance.

Best regards,
Brent Sanford

P.S. If there are any Mac users on the development team who could provide direct guidance, that would be extremely helpful.

**Comment by acolite** [comment]
Hi Brent

It is unfortunate that the installation caused you frustration! Feel free to contact me sooner rather than later to help resolve issues you may encounter. 🙂

I don't have access to an ARM Mac, and so cannot test the installation or processing on that platform. I hope to convince the right people to provide me with such a machine in the future. I rely heavily on the conda platform to provide compatible packages for this architecture. I presume you use conda and conda-forge to set up the environment?

It seems that with recent updates to GDAL, some support libraries were separated from the main package, and a [similar problem](https://odnature.naturalsciences.be/remsem/acolite-forum/viewtopic.php?f=4&t=505 
) was experienced by another (Linux) user, which appeared to be solved by installing libgdal-netcdf. I did update the [ReadMe a few days](https://github.com/acolite/acolite?tab=readme-ov-file#dependencies) ago, and so maybe you have installed this package already.  If you haven't, could you give this a try and report back?

Quinten

**Comment by Brent0423** [comment]
Thank you for the quick reply. As I am reading: The error messages indicate that the GDAL plugins for HDF5 and JP2OpenJPEG are not compatible with your system architecture. This is likely because your system is ARM64 (Apple Silicon), but the plugins are built for x86_64. Could you verify that for me?

I am currently using Anaconda, do you think it would work to convert .nc to .tif using something like this:

`from osgeo import gdal

def nc_to_geotiff(nc_file, variable):
    gdal.UseExceptions()
    try:
        ds = gdal.Open(nc_file)
        subdatasets = ds.GetSubDatasets()
    except Exception as e:
        print(f"Failed to open NetCDF file: {nc_file}\n{e}")
        return

    print("Available variables in NetCDF:")
    for sds in subdatasets:
        variable_name = sds[0].split(':')[-1]
        print(variable_name)

    subdataset_name = None
    for sds in subdatasets:
        if variable in sds[0]:
            subdataset_name = sds[0]
            break

    if subdataset_name:
        try:
            sub_ds = gdal.Open(subdataset_name)
            if sub_ds is None:
                print(f"Subdataset {subdataset_name} could not be opened.")
                return
            outfile = f"{variable}.tif"
            gdal.Translate(outfile, subdataset_name)
            print(f"Wrote {outfile}")
        except Exception as e:
            print(f"Failed to convert {variable}: {e}")
    else:
        print(f"Variable '{variable}' not found in subdatasets.")

if __name__ == "__main__":
    nc_file = "/Users/brentsanford/Desktop/Output/S2B_MSI_2024_05_31_15_55_57_T17RQK_L2W.nc"
    variables = ['Rrs_442', 'Rrs_492', 'Rrs_559', 'Rrs_665', 'Rrs_704', 
                 'Rrs_739', 'Rrs_780', 'Rrs_833', 'Rrs_864', 'Rrs_1610', 'Rrs_2186']
    for var in variables:
        print(f"Processing variable: {var}")
        nc_to_geotiff(nc_file, var)`

I really appreciate your opinion and advice.

**Comment by acolite** [comment]
Hi Brent

Conda should install the osx-arm64 version of those packages, unless you have made an explicit osx-64 (intel) installation. (Which presumably should work fine under Rosetta 2 emulation as well.)

Could you provide the outputs of "conda list" in the environment you use for ACOLITE, and of "conda info"?

Quinten

**Comment by Brent0423** [comment]
Ok here is that information, really appreciate the help.

# packages in environment at /Users/brentsanford/miniforge3/envs/acolite:
#
# Name                    Version                   Build  Channel
blosc                     1.21.6               h5499902_0    conda-forge
bzip2                     1.0.8                h99b78c6_7    conda-forge
c-ares                    1.34.2               h7ab814d_0    conda-forge
ca-certificates           2024.8.30            hf0a4a13_0    conda-forge
freexl                    2.0.0                hfbad9fb_0    conda-forge
gdal                      3.9.3            py39h1f2ab71_2    conda-forge
geos                      3.13.0               hf9b8971_0    conda-forge
geotiff                   1.7.3                h82bf549_3    conda-forge
giflib                    5.2.2                h93a5062_0    conda-forge
hdf4                      4.2.15               h2ee6834_7    conda-forge
hdf5                      1.14.3          nompi_hec07895_105    conda-forge
icu                       75.1                 hfee45f7_0    conda-forge
json-c                    0.18                 he4178ee_0    conda-forge
krb5                      1.21.3               h237132a_0    conda-forge
lerc                      4.0.0                h9a09cb3_0    conda-forge
libaec                    1.1.3                hebf3989_0    conda-forge
libarchive                3.7.4                h83d404f_0    conda-forge
libblas                   3.9.0           25_osxarm64_openblas    conda-forge
libcblas                  3.9.0           25_osxarm64_openblas    conda-forge
libcurl                   8.10.1               h13a7ad3_0    conda-forge
libcxx                    19.1.3               ha82da77_0    conda-forge
libdeflate                1.22                 hd74edd7_0    conda-forge
libedit                   3.1.20191231         hc8eb9b7_2    conda-forge
libev                     4.33                 h93a5062_2    conda-forge
libexpat                  2.6.3                hf9b8971_0    conda-forge
libffi                    3.4.2                h3422bc3_5    conda-forge
libgdal-core              3.9.3                hb8ac103_2    conda-forge
libgdal-hdf4              3.9.3                h30f80ea_2    conda-forge
libgdal-hdf5              3.9.3                hb8bf4f1_2    conda-forge
libgdal-jp2openjpeg       3.9.3                h8e7f578_2    conda-forge
libgdal-netcdf            3.9.3                hf38e6e6_2    conda-forge
libgfortran               5.0.0           13_2_0_hd922786_3    conda-forge
libgfortran5              13.2.0               hf226fd6_3    conda-forge
libiconv                  1.17                 h0d3ecfb_2    conda-forge
libjpeg-turbo             3.0.0                hb547adb_1    conda-forge
libkml                    1.3.0             he250239_1021    conda-forge
liblapack                 3.9.0           25_osxarm64_openblas    conda-forge
libnetcdf                 4.9.2           nompi_he469be0_114    conda-forge
libnghttp2                1.64.0               h6d7220d_0    conda-forge
libopenblas               0.3.28          openmp_h517c56d_0    conda-forge
libpng                    1.6.44               hc14010f_0    conda-forge
librttopo                 1.1.0               ha2cf0f4_17    conda-forge
libspatialite             5.1.0               hffd3212_11    conda-forge
libsqlite                 3.47.0               hbaaea75_1    conda-forge
libssh2                   1.11.0               h7a5bd25_0    conda-forge
libtiff                   4.7.0                hfce79cd_1    conda-forge
libwebp-base              1.4.0                h93a5062_0    conda-forge
libxml2                   2.13.4               h8424949_1    conda-forge
libzip                    1.11.1               hfc4440f_0    conda-forge
libzlib                   1.3.1                h8359307_2    conda-forge
llvm-openmp               19.1.2               hb52a8e5_0    conda-forge
lz4-c                     1.9.4                hb7217d7_0    conda-forge
lzo                       2.10              h93a5062_1001    conda-forge
minizip                   4.0.7                h27ee973_0    conda-forge
ncurses                   6.5                  h7bae524_1    conda-forge
numpy                     2.0.2            py39hd1e06cf_0    conda-forge
openjpeg                  2.5.2                h9f1df11_0    conda-forge
openssl                   3.3.2                h8359307_0    conda-forge
pcre2                     10.44                h297a79d_2    conda-forge
pip                       24.3.1             pyh8b19718_0    conda-forge
proj                      9.5.0                h61a8e3e_0    conda-forge
python                    3.9.20          h9e33284_1_cpython    conda-forge
python_abi                3.9                      5_cp39    conda-forge
readline                  8.2                  h92ec313_1    conda-forge
setuptools                75.1.0             pyhd8ed1ab_0    conda-forge
snappy                    1.2.1                hd02b534_0    conda-forge
sqlite                    3.47.0               hcd14bea_1    conda-forge
tk                        8.6.13               h5083fa2_1    conda-forge
tzdata                    2024b                hc8b5060_0    conda-forge
uriparser                 0.9.8                h00cdb27_0    conda-forge
wheel                     0.44.0             pyhd8ed1ab_0    conda-forge
xerces-c                  3.2.5                h92fc2f4_2    conda-forge
xz                        5.2.6                h57fd34a_0    conda-forge
zlib                      1.3.1                h8359307_2    conda-forge
zstd                      1.5.6                hb46c0d2_0    conda-forge

     active environment : acolite
    active env location : /Users/brentsanford/miniforge3/envs/acolite
            shell level : 3
       user config file : /Users/brentsanford/.condarc
 populated config files : /Users/brentsanford/miniforge3/.condarc
                          /Users/brentsanford/.condarc
          conda version : 24.9.0
    conda-build version : not installed
         python version : 3.12.7.final.0
                 solver : classic
       virtual packages : __archspec=1=m1
                          __conda=24.9.0=0
                          __osx=14.4=0
                          __unix=0=0
       base environment : /Users/brentsanford/miniforge3  (writable)
      conda av data dir : /Users/brentsanford/miniforge3/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/osx-arm64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/osx-arm64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-arm64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /Users/brentsanford/miniforge3/pkgs
                          /Users/brentsanford/.conda/pkgs
       envs directories : /Users/brentsanford/miniforge3/envs
                          /Users/brentsanford/.conda/envs
               platform : osx-arm64
             user-agent : conda/24.9.0 requests/2.32.3 CPython/3.12.7 Darwin/23.4.0 OSX/14.4
                UID:GID : 501:20
             netrc file : None
           offline mode : False

**Comment by Brent0423** [comment]
Ok here is that information:`     active environment : acolite
    active env location : /Users/brentsanford/miniforge3/envs/acolite
            shell level : 3
       user config file : /Users/brentsanford/.condarc
 populated config files : /Users/brentsanford/miniforge3/.condarc
                          /Users/brentsanford/.condarc
          conda version : 24.9.0
    conda-build version : not installed
         python version : 3.12.7.final.0
                 solver : classic
       virtual packages : __archspec=1=m1
                          __conda=24.9.0=0
                          __osx=14.4=0
                          __unix=0=0
       base environment : /Users/brentsanford/miniforge3  (writable)
      conda av data dir : /Users/brentsanford/miniforge3/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/osx-arm64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/osx-arm64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-arm64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /Users/brentsanford/miniforge3/pkgs
                          /Users/brentsanford/.conda/pkgs
       envs directories : /Users/brentsanford/miniforge3/envs
                          /Users/brentsanford/.conda/envs
               platform : osx-arm64
             user-agent : conda/24.9.0 requests/2.32.3 CPython/3.12.7 Darwin/23.4.0 OSX/14.4
                UID:GID : 501:20
             netrc file : None
           offline mode : False`

`# packages in environment at /Users/brentsanford/miniforge3/envs/acolite:
#
# Name                    Version                   Build  Channel
blosc                     1.21.6               h5499902_0    conda-forge
bzip2                     1.0.8                h99b78c6_7    conda-forge
c-ares                    1.34.2               h7ab814d_0    conda-forge
ca-certificates           2024.8.30            hf0a4a13_0    conda-forge
freexl                    2.0.0                hfbad9fb_0    conda-forge
gdal                      3.9.3            py39h1f2ab71_2    conda-forge
geos                      3.13.0               hf9b8971_0    conda-forge
geotiff                   1.7.3                h82bf549_3    conda-forge
giflib                    5.2.2                h93a5062_0    conda-forge
hdf4                      4.2.15               h2ee6834_7    conda-forge
hdf5                      1.14.3          nompi_hec07895_105    conda-forge
icu                       75.1                 hfee45f7_0    conda-forge
json-c                    0.18                 he4178ee_0    conda-forge
krb5                      1.21.3               h237132a_0    conda-forge
lerc                      4.0.0                h9a09cb3_0    conda-forge
libaec                    1.1.3                hebf3989_0    conda-forge
libarchive                3.7.4                h83d404f_0    conda-forge
libblas                   3.9.0           25_osxarm64_openblas    conda-forge
libcblas                  3.9.0           25_osxarm64_openblas    conda-forge
libcurl                   8.10.1               h13a7ad3_0    conda-forge
libcxx                    19.1.3               ha82da77_0    conda-forge
libdeflate                1.22                 hd74edd7_0    conda-forge
libedit                   3.1.20191231         hc8eb9b7_2    conda-forge
libev                     4.33                 h93a5062_2    conda-forge
libexpat                  2.6.3                hf9b8971_0    conda-forge
libffi                    3.4.2                h3422bc3_5    conda-forge
libgdal-core              3.9.3                hb8ac103_2    conda-forge
libgdal-hdf4              3.9.3                h30f80ea_2    conda-forge
libgdal-hdf5              3.9.3                hb8bf4f1_2    conda-forge
libgdal-jp2openjpeg       3.9.3                h8e7f578_2    conda-forge
libgdal-netcdf            3.9.3                hf38e6e6_2    conda-forge
libgfortran               5.0.0           13_2_0_hd922786_3    conda-forge
libgfortran5              13.2.0               hf226fd6_3    conda-forge
libiconv                  1.17                 h0d3ecfb_2    conda-forge
libjpeg-turbo             3.0.0                hb547adb_1    conda-forge
libkml                    1.3.0             he250239_1021    conda-forge
liblapack                 3.9.0           25_osxarm64_openblas    conda-forge
libnetcdf                 4.9.2           nompi_he469be0_114    conda-forge
libnghttp2                1.64.0               h6d7220d_0    conda-forge
libopenblas               0.3.28          openmp_h517c56d_0    conda-forge
libpng                    1.6.44               hc14010f_0    conda-forge
librttopo                 1.1.0               ha2cf0f4_17    conda-forge
libspatialite             5.1.0               hffd3212_11    conda-forge
libsqlite                 3.47.0               hbaaea75_1    conda-forge
libssh2                   1.11.0               h7a5bd25_0    conda-forge
libtiff                   4.7.0                hfce79cd_1    conda-forge
libwebp-base              1.4.0                h93a5062_0    conda-forge
libxml2                   2.13.4               h8424949_1    conda-forge
libzip                    1.11.1               hfc4440f_0    conda-forge
libzlib                   1.3.1                h8359307_2    conda-forge
llvm-openmp               19.1.2               hb52a8e5_0    conda-forge
lz4-c                     1.9.4                hb7217d7_0    conda-forge
lzo                       2.10              h93a5062_1001    conda-forge
minizip                   4.0.7                h27ee973_0    conda-forge
ncurses                   6.5                  h7bae524_1    conda-forge
numpy                     2.0.2            py39hd1e06cf_0    conda-forge
openjpeg                  2.5.2                h9f1df11_0    conda-forge
openssl                   3.3.2                h8359307_0    conda-forge
pcre2                     10.44                h297a79d_2    conda-forge
pip                       24.3.1             pyh8b19718_0    conda-forge
proj                      9.5.0                h61a8e3e_0    conda-forge
python                    3.9.20          h9e33284_1_cpython    conda-forge
python_abi                3.9                      5_cp39    conda-forge
readline                  8.2                  h92ec313_1    conda-forge
setuptools                75.1.0             pyhd8ed1ab_0    conda-forge
snappy                    1.2.1                hd02b534_0    conda-forge
sqlite                    3.47.0               hcd14bea_1    conda-forge
tk                        8.6.13               h5083fa2_1    conda-forge
tzdata                    2024b                hc8b5060_0    conda-forge
uriparser                 0.9.8                h00cdb27_0    conda-forge
wheel                     0.44.0             pyhd8ed1ab_0    conda-forge
xerces-c                  3.2.5                h92fc2f4_2    conda-forge
xz                        5.2.6                h57fd34a_0    conda-forge
zlib                      1.3.1                h8359307_2    conda-forge
zstd                      1.5.6                hb46c0d2_0    conda-forge`

**Comment by Brent0423** [comment]
netcdf4 1.7.2 pypi_0    pypi

**Comment by acolite** [comment]
Hi Brent

Your build for libgdal-netcdf matches with the osx-arm64 build on conda-forge, so this seems correct. You are sure the NetCDF->TIF output of ACOLITE is still broken in this environment?

Can you try running the following code in this environment, and provide the outputs?

```
import os 
import numpy as np
from osgeo import osr, gdal
print(gdal.__version__, gdal.__file__)
f = '/Users/brentsanford/Desktop/Output/S2B_MSI_2024_05_31_15_55_57_T17RQK_L2W.nc'
ds = 'Rrs_442'
outfile = os.path.dirname(f) + os.sep + os.path.basename(f).replace('.nc','_{}.tif'.format(ds))
netcdf_dataset = 'NETCDF:"{}":{}'.format(f, ds)
print(netcdf_dataset)
dt = gdal.Translate(outfile, netcdf_dataset, noData = np.nan, format = 'GTiff', creationOptions = None)
with gdal.Open(outfile) as d:
    md = d.GetMetadata_Dict()
    data = d.ReadAsArray()
print(md)
print(data.shape, data.dtype)
```

Quinten

**Comment by Brent0423** [comment]
I am just now getting back to this and this is what I got: (gdal_env) brentsanford@Brents-MacBook-Pro Acolite Official Version % /Users/brentsanford/miniconda3/bin/python "/Use
rs/brentsanford/Acolite Official Version/test2.py"
3.9.3 /Users/brentsanford/miniconda3/lib/python3.12/site-packages/osgeo/gdal.py
NETCDF:"/Users/brentsanford/Desktop/Output/S2B_MSI_2024_05_31_15_55_57_T17RQK_L2W.nc":Rrs_442
/Users/brentsanford/miniconda3/lib/python3.12/site-packages/osgeo/gdal.py:312: FutureWarning: Neither gdal.UseExceptions() nor gdal.DontUseExceptions() has been explicitly called. In GDAL 4.0, exceptions will be enabled by default.
  warnings.warn(
ERROR 1: netcdf error #-49 : NetCDF: Variable not found .
at (/Users/runner/miniforge3/conda-bld/libgdal-core_1730218201251/work/frmts/netcdf/netcdfdataset.cpp,NCDFOpenSubDataset,11754)

Warning 1: NETCDF:"/Users/brentsanford/Desktop/Output/S2B_MSI_2024_05_31_15_55_57_T17RQK_L2W.nc":Rrs_442 is a netCDF file, but Rrs_442 is not a variable.
ERROR 4: NETCDF:"/Users/brentsanford/Desktop/Output/S2B_MSI_2024_05_31_15_55_57_T17RQK_L2W.nc":Rrs_442: No such file or directory
Traceback (most recent call last):
  File "/Users/brentsanford/Acolite Official Version/test2.py", line 10, in <module>
    dt = gdal.Translate(outfile, netcdf_dataset, noData = np.nan, format = 'GTiff', creationOptions = None)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/brentsanford/miniconda3/lib/python3.12/site-packages/osgeo/gdal.py", line 844, in Translate
    return TranslateInternal(destName, srcDS, opts, callback, callback_data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/brentsanford/miniconda3/lib/python3.12/site-packages/osgeo/gdal.py", line 8978, in TranslateInternal
    return _gdal.TranslateInternal(*args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Received a NULL pointer.

**Comment by acolite** [comment]
Hi Brent

Thanks for testing. With the message "... is a netCDF file, but Rrs_442 is not a variable" it seems that the NetCDF file is correctly recognised, but there is an issue with accessing the variable inside.

Could you run the following, using the netCDF4 package to list the variables:

```
from netCDF4 import Dataset
file = '/Users/brentsanford/Desktop/Output/S2B_MSI_2024_05_31_15_55_57_T17RQK_L2W.nc'
with Dataset(file, 'r') as f:
    print(f.variables.keys())
```

If the variable is listed, could you try the same script as in the previous post and set this just after the gdal import:

```
gdal.UseExceptions()
```

This may hopefully provide additional information during the exception.

Quinten

**Comment by Brent0423** [comment]
here was the output: (gdal_env) ***@***.*** Acolite
Official Version % /Users/brentsanford/miniconda3/bin/python "/Use
rs/brentsanford/Acolite Official Version/test_nc.py"
Traceback (most recent call last):
  File "/Users/brentsanford/Acolite Official Version/test_nc.py", line 1,
in <module>
    from netCDF4 import Dataset
ModuleNotFoundError: No module named 'netCDF4'

**Comment by acolite** [comment]
Hi Brent

Could you install netCDF4 in this environment, or run this test in the environment used for ACOLITE?

Quinten

**Comment by Brent0423** [comment]
(gdal_env) ***@***.*** Acolite Official Version % conda
install -c conda-forge netcdf4
Collecting package metadata (current_repodata.json): done
Solving environment: done

# All requested packages already installed.

(gdal_env) ***@***.*** Acolite Official Version %
/Users/brentsanford/miniconda3/bin/python "/Use
rs/brentsanford/Acolite Official Version/test_nc.py"
Traceback (most recent call last):
  File "/Users/brentsanford/Acolite Official Version/test_nc.py", line 1,
in <module>
    from netCDF4 import Dataset
ModuleNotFoundError: No module named 'netCDF4'

**Comment by acolite** [comment]
Hi Brent

This is slightly bizarre to me! Could you printout the CONDA environment variables in your test_nc.py script?

E.g. by adding at the top:

```
import os
print(os.environ['CONDA_DEFAULT_ENV'])
print(os.environ['CONDA_PREFIX'])
```

Edit: This may occur because you use the Python from another environment? E.g. by running 
 "/Users/brentsanford/miniconda3/bin/python"

Quinten

**Comment by Brent0423** [comment]
this was the output: (gdal_env) ***@***.*** Acolite
Official Version % /Users/brentsanford/miniconda3/bin/python "/Users/b
rentsanford/Acolite Official Version/test_nc.py"
Conda Environment Info:
CONDA_DEFAULT_ENV: gdal_env
CONDA_PREFIX: /Users/brentsanford/miniconda3/envs/gdal_env

Error importing netCDF4: No module named 'netCDF4'
Current Python path:
['/Users/brentsanford/Acolite Official Version',
'/Users/brentsanford/miniconda3/lib/python312.zip',
'/Users/brentsanford/miniconda3/lib/python3.12',
'/Users/brentsanford/miniconda3/lib/python3.12/lib-dynload',
'/Users/brentsanford/miniconda3/lib/python3.12/site-packages']

**Comment by acolite** [comment]
Hi Brent

Could you run in the terminal:

```
which python
```

and use that one from your environment instead of the Python in base?

Quinten

**Comment by Brent0423** [comment]
yes it output: (gdal_env) ***@***.*** Acolite Official
Version % which python
/Users/brentsanford/miniconda3/envs/gdal_env/bin/python
(gdal_env) ***@***.*** Acolite Official Version %
/Users/brentsanford/miniconda3/envs/gdal_env/bin/python
"/Users/brentsanford/Acolite Official Version/test_nc.py"
Conda Environment Info:
CONDA_DEFAULT_ENV: gdal_env
CONDA_PREFIX: /Users/brentsanford/miniconda3/envs/gdal_env

netCDF4 successfully imported

Available variables:
dict_keys(['transverse_mercator', 'x', 'y', 'lon'])
(gdal_env) ***@***.*** Acolite Official Version %

**Comment by acolite** [comment]
Hi Brent

Ok, so for some reason that NetCDF file doesn't have the Rrs_442 dataset to output (it just has longitude as a 2D dataset). Perhaps the processing was interrupted or crashed during the L2W generation. No surprise then that the gdal NetCDF reader fails to open this dataset from the nc file.

Could you rerun the processing in the environment with libgdal-netcdf installed and check whether the tif output is fixed? If not it could be useful to look at the log files what goes wrong.

Quinten

**Comment by Brent0423** [comment]
It appears to have fixed the problem, I will keep you updated as I begin
working with it. Thanks again for your help.

**Comment by acolite** [comment]
Hi Brent

Thanks for the update! Probably the only issue was the libgdal-netcdf package that needed to be installed for the NetCDF->GeoTIFF conversion.

Quinten
