### ISSUE TITLE
ImportError: DLL load failed: The specified module could not be found.

### ISSUE THREAD

**Issue by acolite** [acolite/acolite#9]
I have a new problem. When I run this program, "DLL load failed", the specific log is as follows:Running ACOLITE processing on win32
ACOLITE processing messages will be logged to file.
Processing error:
DLL load failed:The specified module could not be found.
Traceback (most recent call last):
  File "E:\Download\acolite-main\acolite-main\acolite\acolite\acolite_gui.py", line 25, in run
    mp.Process.run(self)
  File "D:\python37\lib\multiprocessing\process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "E:\Download\acolite-main\acolite-main\acolite\acolite\acolite_run.py", line 135, in acolite_run
    ret = ac.acolite.acolite_l2w(l2r, settings=l2r_setu)
  File "E:\Download\acolite-main\acolite-main\acolite\acolite\acolite_l2w.py", line 23, in acolite_l2w
    import skimage.color
  File "D:\python37\lib\site-packages\skimage\__init__.py", line 127, in <module>
    from .util.dtype import (img_as_float32,
  File "D:\python37\lib\site-packages\skimage\util\__init__.py", line 17, in <module>
    from ._map_array import map_array
  File "D:\python37\lib\site-packages\skimage\util\_map_array.py", line 2, in <module>
    from ._remap import _map_array
ImportError: DLL load failed: The specified module could not be found.

_Originally posted by @LH002 in https://github.com/acolite/acolite/issues/8#issuecomment-890449632_

**Comment by acolite** [comment]
This seems to an issue with your installation of scikit-image, there is a discussion on the scikit-image GitHub page: https://github.com/scikit-image/scikit-image/issues/4780

Can you successfully run "import skimage.color" in your own Python code?

Could you try and limit issues to a single issue, so these are easier to track, and potentially useful for other people?

Quinten

**Comment by LH002** [comment]
Thank you for your reminder. I found that the version of scikit image I installed was 0.18.2, so there was a problem. Later, I installed 0.17.2, and the problem can be solved.

**Comment by LH002** [comment]
Thank you very much for your timely reply and reminder. I can debug the product I want now. Thank you for your reply these days.

**Comment by acolite** [comment]
Seems to be solved by reinstalling scikit-image
